name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CUDA Keyring
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
          sudo dpkg -i cuda-keyring_1.0-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglew-dev libglfw3-dev mesa-common-dev build-essential libxrandr-dev libxinerama-dev libxcursor-dev

      - name: Build GLFW from source
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw
          mkdir build
          cd build
          cmake .. -DGLFW_BUILD_WAYLAND=OFF -DGLFW_BUILD_X11=ON
          make
          sudo make install


  
      - name: Configure and build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make     
      
